version: "3.7"

services:
  app:
    image: anonymoussystems/torbox-media-center:latest
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    privileged: true
    environment:
      - TORBOX_API_KEY=<api_key>
      - MOUNT_METHOD=fuse
      - MOUNT_PATH=/torbox
      - SCAN_METADATA=true
      - MOUNT_REFRESH_TIME=ultra_fast
    volumes:
      - ${UMBREL_ROOT}/data/storage/downloads/torbox/cloud:/torbox:rshared
    restart: unless-stopped
