version: "3.7"

services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: sparkles-hello-world_pyload_1
      APP_PORT: 8000
      PROXY_AUTH_ADD: "false"
    
  pyload:
    image: lscr.io/linuxserver/pyload-ng
    container_name: pyload-ng
    environment:
      - TZ=Etc/UTC
    volumes:
      - ${APP_DATA_DIR}/data/pyload:/config
      - ${UMBREL_ROOT}/data/storage/downloads/pyload:/downloads
    restart: unless-stopped
