version: "3.7"

services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: stefan-pyload_app_1
      APP_PORT: 8000
    
  app:
    image: lscr.io/linuxserver/pyload-ng
    environment:
      - TZ=Etc/UTC
    ports:
      - 8000:8000
    volumes:
      - ${APP_DATA_DIR}/data/pyload:/config
      - ${UMBREL_ROOT}/data/storage/downloads/pyload:/downloads
    restart: unless-stopped
